### GET ALL USERS
GET http://localhost:3000/users HTTP/1.1

### GET specific user
GET http://localhost:3000/users/10 HTTP/1.1

### Add user
POST http://localhost:3000/users HTTP/1.1

Content-Type: application/json

{
    "user_name": "jDoe", 
    "first_name": "John", 
    "last_name": "Doe", 
    "registered": true, 
    "active": false, 
    "sso": true, 
    "pin": 1234, 
    "lockout_end_date": "1973-08-26 20:55:00+07:30", 
    "password_end_date": "2013-09-14 14:03:13+08", 
    "is_deleted": false, 
    "source_client_id":1 
}